#[derive(Debug, Clone, Copy)]
pub enum Instruction {
    NoOperation,
    Halt,
    Add                   { reg_a: u8, reg_b: u8, reg_c: u8 },
    Subtract              { reg_a: u8, reg_b: u8, reg_c: u8 },
    Multiply              { reg_a: u8, reg_b: u8, reg_c: u8 },
    Divide                { reg_a: u8, reg_b: u8, reg_c: u8 },
    Modulo                { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseAnd            { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseNand           { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseOr             { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseNor            { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseXor            { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseXnor           { reg_a: u8, reg_b: u8, reg_c: u8 },
    BitwiseNot            { reg_a: u8, reg_b: u8 },
    RightShift            { reg_a: u8, reg_b: u8 },
    LeftShift             { reg_a: u8, reg_b: u8 },
    LoadImmediate         { reg_a: u8, immediate: u8 },
    AddImmediate          { reg_a: u8, immediate: i32 },
    SubtractImmediate     { reg_a: u8, immediate: i32 },
    MultiplyImmediate     { reg_a: u8, immediate: i32 },
    DivideImmediate       { reg_a: u8, immediate: i32 },
    Jump                  { reg_a: u8 },
    Branch                { address: u16 },
    Call                  { condition_flag: u8, address: u16 },
    Return,
    MemoryLoad            { reg_a: u8, reg_b: u8, offset: u8 },
    MemoryStore           { reg_a: u8, reg_b: u8, offset: u8 },
    Draw                  { reg_x: u8, reg_y: u8, reg_r: u8, reg_g: u8, reg_b: u8 },
    PushBuffer,
    ControllerPad         { reg_a: u8 },
    RandomNumberGenerator { reg_a: u8 },
}