use std::error::Error;

use common::hardware;

use crate::{code_gen, parser, preprocessor};

pub fn compile(input: Vec<String>, format: OutputFormat) -> Vec<Result<String, Box<dyn Error>>> {
    let source = match preprocessor::process_program(input) {
        Ok(lines) => lines,
        Err(e) => return vec![Err(Box::new(e))],
    };

    let mut output: Vec<Result<String, Box<dyn Error>>> = Vec::new();

    let header = match format {
        OutputFormat::Binary => "!format [c16 binary]",
        OutputFormat::Hexadecimal => "!format [c16 hexadecimal]",
        OutputFormat::Assembly => "!notrunable",
    };
    output.push(Ok("# Lines starting with '#' are ignored".into()));
    output.push(Ok("# Lines starting with '!' contain information for the virtual machine".into()));
    output.push(Ok("# Autogenerated by xis16-compiler".into()));
    output.push(Ok("".into()));
    output.push(Ok(header.into()));
    output.push(Ok("".into()));

    for (original_line, line) in source {
        let result: Result<String, Box<dyn Error>> = match parser::parse_line(line, original_line) {
            Ok(instruction) => match format {
                OutputFormat::Binary => Ok(code_gen::to_binary_string(&instruction)),
                OutputFormat::Hexadecimal => Ok(code_gen::to_hexadecimal_string(&instruction)),
                OutputFormat::Assembly => Ok(code_gen::to_assembly_string(&instruction)),
            },
            Err(e) => Err(e),
        };
        output.push(result);
    }

    println!("Used {} instruction addresses ({}%)", output.len(),  output.len() as f32 / hardware::INSTRUCTION_MEM_SIZE as f32 * 100.0);
    output
}

#[allow(dead_code)]
pub enum OutputFormat {
    Binary,
    Hexadecimal,
    Assembly,
}