use std::error::Error;

pub mod parser;

pub fn compile(source: &[String], format: OutputFormat, ) -> Vec<Result<String, Box<dyn Error>>> {
    let mut output: Vec<Result<String, Box<dyn Error>>> = Vec::new();

    let header = match format {
        OutputFormat::Binary => "!format [c16 binary]",
        OutputFormat::Hexadecimal => "!format [c16 hexadecimal]",
        OutputFormat::Assembly => "!notrunable",
    };

    output.push(Ok("# Lines starting with '#' are ignored".into()));
    output.push(Ok("# Lines starting with '!' contain special information for the virtual machine".into()));
    output.push(Ok("# Autogenerated by xis16-compiler".into()));
    output.push(Ok("".into()));
    output.push(Ok(header.into()));
    output.push(Ok("".into()));

    for (ln, line) in source.iter().enumerate() {
        if line.trim().is_empty() || line.trim_start().starts_with("//") {
            continue;
        }

        let result: Result<String, Box<dyn Error>> = match parser::parse_line(line, ln) {
            Ok(instruction) => match format {
                OutputFormat::Binary => Ok(instruction.to_binary_string()),
                OutputFormat::Hexadecimal => Ok(instruction.to_hex_string()),
                OutputFormat::Assembly => Ok(instruction.to_assembly_string()),
            },
            Err(e) => Err(e),
        };

        output.push(result);
    }

    output
}

#[allow(dead_code)]
pub enum OutputFormat {
    Binary,
    Hexadecimal,
    Assembly,
}