use std::error::Error;

pub mod parser;

pub fn compile(source: &[String], format: OutputFormat) -> Result<Vec<String>, Box<dyn Error>> {
    let mut output = Vec::new();

    match format {
        OutputFormat::Binary => {
            output.push("# Lines starting with '#' are ignored".into());
            output.push("# Autogenerated by xis16-compiler".into());
            output.push("# c16 Binary Code".into());
            output.push("".into());

            for (ln, line) in source.iter().enumerate() {
                if line.trim().is_empty() || line.trim_start().starts_with("//") {
                    continue;
                }
                let instruction = parser::parse_line(line, ln)?;
                output.push(instruction.to_binary_string());
            }
        }
        OutputFormat::Hex => {
            output.push("# Lines starting with '#' are ignored".into());
            output.push("# Autogenerated by xis16-compiler".into());
            output.push("# c16 Hexadecimal Code".into());
            output.push("".into());

            for (ln, line) in source.iter().enumerate() {
                if line.trim().is_empty() || line.trim_start().starts_with("//") {
                    continue;
                }
                let instruction = parser::parse_line(line, ln)?;
                output.push(instruction.to_hex_string());
            }
        }
        OutputFormat::Assembly => {
            output.push("# Lines starting with '#' are ignored".into());
            output.push("# Autogenerated by xis16-compiler".into());
            output.push("# Generated xis16 Code".into());
            output.push("".into());

            for (ln, line) in source.iter().enumerate() {
                if line.trim().is_empty() || line.trim_start().starts_with("//") {
                    continue;
                }
                let instruction = parser::parse_line(line, ln)?;
                output.push(instruction.to_assembly_string());
            }   
        }
    }

    

    Ok(output)
}

#[allow(dead_code)]
pub enum OutputFormat {
    Binary,
    Hex,
    Assembly,
}