use std::error::Error;

pub mod parser;
pub mod code_gen;

pub fn compile(source: &[String], format: OutputFormat, ) -> Vec<Result<String, Box<dyn Error>>> {
    let mut output: Vec<Result<String, Box<dyn Error>>> = Vec::new();

    let header = match format {
        OutputFormat::Binary => "!format [c16 binary]",
        OutputFormat::Hexadecimal => "!format [c16 hexadecimal]",
        OutputFormat::Assembly => "!notrunable",
    };

    output.push(Ok("# Lines starting with '#' are ignored".into()));
    output.push(Ok("# Lines starting with '!' contain information for the virtual machine".into()));
    output.push(Ok("# Autogenerated by xis16-compiler".into()));
    output.push(Ok("".into()));
    output.push(Ok(header.into()));
    output.push(Ok("".into()));

    for (ln, line) in source.iter().enumerate() {
        let code_part = line.split("//").next().unwrap().trim();

        if code_part.is_empty() {
            continue;
        }

        let result: Result<String, Box<dyn Error>> = match parser::parse_line(line, ln) {
            Ok(instruction) => match format {
                OutputFormat::Binary => Ok(code_gen::to_binary_string(&instruction)),
                OutputFormat::Hexadecimal => Ok(code_gen::to_hexadecimal_string(&instruction)),
                OutputFormat::Assembly => Ok(code_gen::to_assembly_string(&instruction)),
            },
            Err(e) => Err(e),
        };

        output.push(result);
    }

    output
}

#[allow(dead_code)]
pub enum OutputFormat {
    Binary,
    Hexadecimal,
    Assembly,
}